name: Binance Screener Scheduler

on:
  schedule:
    # Keep alive every 20 minutes
    - cron: "*/20 * * * *"
    # Run screener every 10 minutes
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  keep-alive:
    if: github.event.schedule == '*/20 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Keep service alive
        run: |
          echo "Pinging service..."
          curl -v https://binance-trade-screener.onrender.com/ping

  run-screener:
    if: github.event.schedule == '*/10 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Run screener and log response
        run: |
          echo "Executing screener..."
          RESPONSE=$(curl -s -w "\nHTTP_CODE:%{http_code}\n" https://binance-trade-screener.onrender.com/run)
          echo "Response from /run endpoint:"
          echo "$RESPONSE"
