name: Binance Screener Scheduler

on:
  schedule:
    # Every 20 minutes -> keep alive
    - cron: "*/20 * * * *"
    # Every 4 hours at :35 (1:35, 5:35, 9:35...)
    - cron: "35 */4 * * *"
  workflow_dispatch: # manual trigger

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Keep alive (ping every 20 mins)
        if: github.event.schedule == '*/20 * * * *'
        run: curl -s https://binance-trade-screener.onrender.com/ping

      - name: Run screener (every 4 hrs)
        if: github.event.schedule == '35 */4 * * *'
        run: curl -s https://binance-trade-screener.onrender.com/run
