name: Binance Screener Scheduler

on:
  schedule:
    - cron: "*/20 * * * *"    # Every 20 mins (ping)
    - cron: "2 */4 * * *"     # Every 4 hrs at xx:02 UTC = xx:32 IST
  workflow_dispatch:

jobs:
  keep-alive:
    if: github.event.schedule == '*/20 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: |
          curl -s https://binance-trade-screener.onrender.com/ping > /dev/null

  run-script:
    if: github.event.schedule == '2 */4 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Binance Screener
        run: |
          python app.py
