name: Binance Screener Scheduler

on:
  schedule:
    - cron: "*/20 * * * *"   # Ping every 20 mins
    - cron: "35 */4 * * *"   # Run every 4 hrs at :35

  workflow_dispatch:

jobs:
  keep-alive:
    if: github.event.schedule == '*/20 * * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render service
        run: |
          curl -s https://binance-trade-screener.onrender.com/ > /dev/null

  run-script:
    if: github.event.schedule == '35 */4 * * *'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Binance Screener
        run: |
          python app.py
